### ISSUE TITLE
Download of Release not working

### ISSUE THREAD

**Issue by pega3** [EndlessSkyCommunity/ESLauncher2#1]
OS: Win64
ESLauncher-Version: 0.4.1

To reproduce:
- started ESLauncher
- selected "Release" radio button
- filled out instance name (rel-0-9-12)
- filled out release number (v.0.9.12)
- pressed "Install"
Tool finds assets, but then aborts with message: 16:09:37 [ERROR] Install failed: Couldn't match any asset against EndlessSky-win64
[ESLauncher2.log](https://github.com/EndlessSkyCommunity/ESLauncher2/files/4737298/ESLauncher2.log)

**Comment by MCOfficer** [comment]
Should be fixed with 80d7eae6b590252330af5541d933c2f04a20a65e.

Please try the executables from https://github.com/EndlessSkyCommunity/ESLauncher2/actions/runs/126201334

**Comment by pega3** [comment]
Still not working. It now downloads the release, but hangs after the unzip message. I waited several minutes and checked in Process Monitor. 
Ran a procmon trace and what sticked out there was that get's a "path not found" on 
....\instances\rel-9-12\endless-sky-win64-0.9.12\changelog
This operation came after a lenghty read of the downloaded zip file. 
It cannot create the changelog directory, because the directory endless-sky-win64-0.9.12 does not exist. It looks a bit as if it's extrapolating the directory name from the zip file, but that directory was never created. 

Hope that makes some form of sense.

**Comment by MCOfficer** [comment]
Oh... it's because the zip contains a directory, probably. That might not be the immediate cause, but it would've caused other problems later. I should've just written the unzip code myself.

**Comment by MCOfficer** [comment]
I extracted the ESPIM zip code into a public method. Both ESPIM and ESL2 will now ditch the top-level directory if needed. 01cef1d00b6a856f6036fa0640d15133af6976ce

https://github.com/EndlessSkyCommunity/ESLauncher2/actions/runs/126327662

**Comment by pega3** [comment]
Almost there. Now the launch doesn't work, because it's looking for the exe in the partent directory and not in the subdirectory.

**Comment by MCOfficer** [comment]
there should be no subdirectory :thinking: Can i see the log?

**Comment by pega3** [comment]
I took build #77. I am installing 0.9.12, the zipfile on github contains a directory. Log is attached. 
Never mind the uninstall, that's already the cleanup for the next test.

[ESLauncher2.log](https://github.com/EndlessSkyCommunity/ESLauncher2/files/4738347/ESLauncher2.log)

**Comment by MCOfficer** [comment]
Works on my machine now :p

https://github.com/EndlessSkyCommunity/ESLauncher2/actions/runs/126839098
